name: Bug Report
description: Report a bug or issue with ngx-vest-forms
title: "[Bug]: "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to report a bug! Please fill out this form to help us understand and resolve the issue.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: What should have happened?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: A clear and concise description of what actually happened.
      placeholder: What actually happened?
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Please provide information about your environment
      placeholder: |
        - ngx-vest-forms version: [e.g. 1.1.0]
        - Angular version: [e.g. 18.0.1]
        - Node.js version: [e.g. 20.11.0]
        - Browser: [e.g. Chrome 125, Safari 17]
        - OS: [e.g. macOS 14.5, Windows 11, Ubuntu 22.04]
    validations:
      required: true

  - type: textarea
    id: reproduction-url
    attributes:
      label: Minimal Reproduction
      description: |
        Please provide a minimal reproduction of the issue. This could be:
        - A link to a StackBlitz/CodeSandbox
        - A GitHub repository
        - Code snippets
      placeholder: |
        Provide a minimal reproduction here...
        
        ```typescript
        // Your reproduction code
        ```

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here, including screenshots if applicable.
      placeholder: Any additional information that might help...

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Before submitting, please confirm:
      options:
        - label: I have searched existing issues to avoid duplicates
          required: true
        - label: I have provided a clear description of the issue
          required: true
        - label: I have included steps to reproduce the issue
          required: true
        - label: I have provided environment information
          required: true