name: Repository Validation
on:
  pull_request:
    paths:
      - '.github/**'
  push:
    branches:
      - master
    paths:
      - '.github/**'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  validate-governance:
    name: Validate Repository Governance
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      - name: Checkout ✅
        uses: actions/checkout@v4
        
      - name: Validate CODEOWNERS syntax 👥
        run: |
          if [ -f ".github/CODEOWNERS" ]; then
            echo "✅ CODEOWNERS file exists"
            # Basic syntax validation
            if grep -q "^[^#]" .github/CODEOWNERS; then
              echo "✅ CODEOWNERS has valid entries"
            else
              echo "❌ CODEOWNERS appears to be empty or only has comments"
              exit 1
            fi
          else
            echo "❌ CODEOWNERS file missing"
            exit 1
          fi
          
      - name: Validate issue templates 📝
        run: |
          if [ -d ".github/ISSUE_TEMPLATE" ]; then
            echo "✅ Issue templates directory exists"
            if [ -f ".github/ISSUE_TEMPLATE/bug_report.yml" ]; then
              echo "✅ Bug report template exists"
            else
              echo "❌ Bug report template missing"
              exit 1
            fi
            if [ -f ".github/ISSUE_TEMPLATE/feature_request.yml" ]; then
              echo "✅ Feature request template exists"
            else
              echo "❌ Feature request template missing"
              exit 1
            fi
          else
            echo "❌ Issue templates directory missing"
            exit 1
          fi
          
      - name: Validate PR template 🔄
        run: |
          if [ -f ".github/pull_request_template.md" ]; then
            echo "✅ Pull request template exists"
          else
            echo "❌ Pull request template missing"
            exit 1
          fi
          
      - name: Validate governance documentation 📚
        run: |
          if [ -f ".github/CONTRIBUTING.md" ]; then
            echo "✅ Contributing guidelines exist"
          else
            echo "❌ Contributing guidelines missing"
            exit 1
          fi
          
          if [ -f ".github/SECURITY.md" ]; then
            echo "✅ Security policy exists"
          else
            echo "❌ Security policy missing"
            exit 1
          fi
          
          if [ -f ".github/GOVERNANCE.md" ]; then
            echo "✅ Governance documentation exists"
          else
            echo "❌ Governance documentation missing"
            exit 1
          fi
          
      - name: Validate ruleset configuration 🛡️
        run: |
          if [ -f ".github/rulesets/master-branch-protection.json" ]; then
            echo "✅ Master branch protection ruleset exists"
            # Basic JSON validation
            if python3 -m json.tool .github/rulesets/master-branch-protection.json > /dev/null; then
              echo "✅ Ruleset JSON is valid"
            else
              echo "❌ Ruleset JSON is invalid"
              exit 1
            fi
          else
            echo "❌ Master branch protection ruleset missing"
            exit 1
          fi
          
      - name: Repository governance summary 📊
        run: |
          echo "## 🏛️ Repository Governance Summary"
          echo ""
          echo "### 📋 Governance Files"
          echo "- [x] CONTRIBUTING.md"
          echo "- [x] SECURITY.md" 
          echo "- [x] GOVERNANCE.md"
          echo "- [x] CODEOWNERS"
          echo ""
          echo "### 📝 Templates"
          echo "- [x] Bug report template"
          echo "- [x] Feature request template"
          echo "- [x] Pull request template"
          echo "- [x] Issue template configuration"
          echo ""
          echo "### 🛡️ Protection Rules"
          echo "- [x] Master branch protection ruleset"
          echo "- [x] Repository validation workflow"
          echo ""
          echo "### 🚀 CI/CD"
          echo "- [x] Enhanced CI workflow"
          echo "- [x] Enhanced CD workflow"
          echo ""
          echo "✅ All repository governance components are properly configured!"